---
title: "Demo_2_Power_2025"
author: "Cris Van Hout"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = FALSE)

# Load relevant libraries
library(dplyr)
library(knitr)
library(ggplot2)

# Set seed for reproducibility
set.seed(123)

# Define simulation parameters
n <- 1000  # sample size
effect_sizes <- seq(0, .6, by = 0.05)  # range of effect sizes to test
alpha <- 0.05  # significance level
iterations <- 1000  # number of simulations
power_results <- data.frame()  # data frame to store power results
q <- 0.3  # Effect allele frequency


# Perform simulations over a range of effect sizes
for (beta in effect_sizes) {
  power_count <- 0  # counter for significant results
  p_values <- numeric(iterations)  # vector to store p-values
  
  for (i in 1:iterations) {
    # Simulate data

    # Define allele counts from frequencies based on Hardy-Weinberg Equilibrium (HWE)
    Nrr <- round((1-q)^2 * n)
    Nra <- round(2 * q * (1-q) * n)
    Naa <- n - Nrr - Nra

    # Define genotype vectors
    Xrr <- rep(0, Nrr)
    Xra <- rep(1, Nra)
    Xaa <- rep(2, Naa)
    x <- c(Xrr, Xra, Xaa)

    x <- rnorm(n, mean = 0, sd = 1)  # predictor variable
    y <- beta * x + rnorm(n, mean = 10, sd = 4)  # outcome variable
    
    # Fit linear model
    model <- lm(y ~ x)
    
    # Extract p-value from the model, and store for later
    p_value <- summary(model)$coefficients[2, 4]
    p_values[i] <- p_value
    
    # Check if p-value is significant, that is, less than the threshold alpha
    if (p_value < alpha) {
      power_count <- power_count + 1
    }
  }
  
  # Calculate statistical power for the current effect size
  power <- power_count / iterations
  
  # Calculate the mean and 90% interquantile interval of p-values
  mean_p <- mean(p_values)
  quantiles <- quantile(p_values, probs = c(0.05, 0.95))
  
  power_results <- rbind(power_results, data.frame(beta = beta, power = power, mean_p = mean_p, lower05 = quantiles[1], upper95 = quantiles[2]))
}

# Print power results
rownames(power_results) <- NULL
#print(power_results) #this is ugly!!
kable(power_results, format = "markdown")


# Plot power vs. effect size 
ggplot(power_results, aes(x = beta)) +
  geom_line(aes(y = power), color = "blue", linewidth = 1) +
  geom_point(aes(y = power), color = "red", size = 2) +
  scale_y_continuous(name = "Power") +
  ylim(0, 1) +
  labs(title = "Power Curve")